import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';

import './globals.css';

import { Footer } from '@/components/navigation/footer';
import { Navbar } from '@/components/navigation/navbar';
import { ThemeProvider } from '@/components/theme/provider';

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Suppress hydration warning due to theme mismatch between server and client
    <html lang='en' suppressHydrationWarning>
      {/* always show scrollbar to avoid layout shift when switching between scrollable and non-scrollable pages */}
      <body
        className={`${jetbrainsMono.variable} overflow-y-scroll font-mono antialiased`}
      >
        <div id='top' />
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          defaultTheme='system'
          attribute='class'
        >
          <div className='flex min-h-screen flex-col items-center justify-center'>
            <Navbar />
            <div className='flex w-full flex-1'>
              <main className='container mx-auto flex flex-col items-center gap-8 p-4 py-16 lg:py-32'>
                {children}
              </main>
            </div>
            <Footer />
          </div>
        </ThemeProvider>
        <div id='bottom' />
      </body>
    </html>
  );
}
