import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

import { DesktopNavbar, MobileNavbar } from '@/components/navigation/navbar';
import { ThemeProvider } from '@/components/theme/provider';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* Permanently show scrollbar to prevent layout shift */}
      <body className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col overflow-y-scroll antialiased`}>
        {/* Apply system theme */}
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {/* Sonner toasts */}
          <Toaster richColors />
          {/* Navbar for desktop */}
          <DesktopNavbar />
          {/* Anchor for the top of the page */}
          <div id='top' />
          {/* Page content */}
          <main className='flex flex-1 flex-col'>{children}</main>
          {/* Anchor for the bottom of the page | Stop the page from becoming scrollable during animation */}
          <div id='bottom' className='p-4' />
          {/* Navbar for mobile */}
          <MobileNavbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
